name: Test Maximize available disk space for build
on: push

jobs:
  test:
    name: Maximize available disk space for build
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master

      - name: Environment report after
        run: |
          echo "Memory and swap:"
          free
          echo
          swapon --show
          echo

          echo "Storage:"
          cat /etc/fstab
          df -h
          echo
          ls -hl /pv.img
          du -sh /pv.img
