name: Test Maximize available disk space for build
on: push

jobs:
  test:
    name: Maximize available disk space for build
    runs-on: ubuntu-latest
    steps:
      - name: Environment report before
        run: |
          echo "Working directory: $(pwd)"
          echo
          ls -al

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 512

      - name: Environment report after
        run: |
          echo "Working directory: $(pwd)"
          echo
          ls -al
