name: Test Stuff
on: push

jobs:
  test:
    name: Test Stuff
    runs-on: ubuntu-latest
    steps:
    - id: sysstat
      name: initialize sysstat
      uses: easimon/sysstat-action@main

    - id: main
      name: make some noise
      shell: bash
      run: |
        # make some noise
        env
        sudo apt-get install -y cryptsetup

        for i in $(seq 1 5); do
          dd if=/dev/zero of=zeros.img bs=1M count=1024
          cryptsetup benchmark
          rm zeros.img
        done
