name: Test Stuff
on: push

jobs:
  test:
     runs-on: ubuntu-20.04
     steps:
      - name: Environment report before
        run: |
          echo "Working directory: $(pwd)"
          echo
          ls -al /mnt
      - name: Maximize build space
        uses: easimon/maximize-build-space@fix/ubuntu-20.04
        with:
          root-reserve-mb: 512
          swap-size-mb: 512
