name: Test Maximize available disk space for build
on: push

jobs:
  test:
    name: Maximize available disk space for build
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v1
        with:
          root-reserve-mb: 512
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
